# Grub configuration generator config
overwrite: false
keepDistributor: false
defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: "saved"
    GRUB_DISABLE_SUBMENU: true
    GRUB_TERMINAL_OUTPUT: "gfxterm"
    GRUB_DISABLE_RECOVERY: true
    GRUB_THEME: "/usr/share/grub/themes/pallasos/theme.txt"
    GRUB_CMDLINE_LINUX_DEFAULT: "quiet splash loglevel=3"
