# Shellprocess module for cleanup
dontChroot: false
timeout: 300
script:
    - "userdel -r pallas"
    - "pacman -Rns --noconfirm calamares archiso kpmcore yaml-cpp || true"
    - "rm -f /etc/sudoers.d/g_wheel"
    - "rm -f /etc/systemd/system/pallas-live-setup.service"
    - "rm -f /etc/systemd/system/pacman-init.service"
    - "rm -f /etc/sddm.conf.d/autologin.conf"
